### ISSUE TITLE
Typo prevents proper registry key set

### ISSUE THREAD

**Issue by lyttek** [dszp/NinjaOne-Scripts#1]
https://github.com/dszp/NinjaOne-Scripts/blob/3439e44e0f1c9ef1d4232b7e1700e227b0a361bd/Browser-and-Office-Autoupdate/Browser-Office-Autoupdate.ps1#L113

When setting the key, the word "key" appears where it shouldn't, creating a new registry key rather than updating.

**Comment by dszp** [comment]
Sorry I missed this earlier @lyttek! I have fixed the key name typo you reported. Thank you very much for the help!
